### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by icarusinthewings** [micahlt/micahlt.github.io#11]
Hey!
Right now if I wanted to, I could easily copy your website and call it my own. I would recommend adding a license to this repository.

**Comment by Semisol** [comment]
> Hey!
> Right now if I wanted to, I could easily copy your website and call it my own. I would recommend adding a license to this repository.

No license == All rights reserved

See [here](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository)

> You're under no obligation to choose a license. However, without a license, **the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work**. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

**Comment by icarusinthewings** [comment]
He has no all rights reserved notice -- Azyan has already copied micah's website for his own without any credit.

**Comment by Semisol** [comment]
@VelocityDesign He technically can submit a DMCA claim. 

By default, on GitHub, everything is all rights reserved.

**Comment by Semisol** [comment]
Just check the link, it obviously says **However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.**

**Comment by Semisol** [comment]
_content has been removed._

**Comment by icarusinthewings** [comment]
Sorry about this misunderstanding, lol. I was (fairly) new to copyright, etc.

**Comment by micahlt** [comment]
> Sorry about this misunderstanding, lol. I was (fairly) new to copyright, etc.

You're good ☺️ have you seen the new site yet?

**Comment by icarusinthewings** [comment]
> > Sorry about this misunderstanding, lol. I was (fairly) new to copyright, etc.
> 
> You're good relaxed have you seen the new site yet?

Yeah. I'd prefer something in between the new and the old, as the new one is a little too minimalistic.
