### ISSUE TITLE
The YouTube link is not accurate.

### ISSUE THREAD

**Issue by w3teal** [micahlt/micahlt.github.io#18]
![2023-12-16 10_47_26-Micah Lindley](https://github.com/micahlt/micahlt.github.io/assets/143163098/11f684d0-419c-4c39-9ef7-fad8ce06eb22)
![2023-12-16 10_47_59-404 Not Found](https://github.com/micahlt/micahlt.github.io/assets/143163098/4815b8b6-1745-4d2e-90ec-bb2ade105dab)

**Comment by micahlt** [comment]
Thanks!  I'll fix this!
