### ISSUE TITLE
Mobile responsiveness

### ISSUE THREAD

**Issue by moeenio** [micahlt/micahlt.github.io#5]
The website doesn't seem to be responsive on mobile.

**Comment by grngxd** [comment]
For me it is

**Comment by moeenio** [comment]
Oh god, you're back from the dead... Your Scratch profile and github projects were completely dead... Well, happy to see you @AyzansAlt !

Other than that, this is a screenshot of the site from latest Chrome for Android :
![Screenshot_2020-05-19-14-06-51](https://user-images.githubusercontent.com/37651007/82324919-b6fa5200-99da-11ea-89df-c3ee3cafe06d.png)

As you can see, the site's definitely not responsive.

**Comment by micahlt** [comment]
@locness3 Yep, it's bad.  I'm working on it, but I stupidly built it with lots of `position: absolute` properties, so it really all needs to be rebuilt.

**Comment by grngxd** [comment]
@Locness3 i kinda died, and by that I mean I moved to Youtube for a while.

**Comment by moeenio** [comment]
oh, what's your channel? also, do you have discord (so we don't clutter this issue with offtopic) ?

**Comment by grngxd** [comment]
https://www.youtube.com/channel/UCaHeNHQ5AFkPyFnekFs2jWg/ and no, alright its  time for me to go back to my grave

**Comment by grngxd** [comment]
congrats on 12^2 commits to the repo.

**Comment by moeenio** [comment]
Congrats on learning exponents @AyzansAlt , in France we learn that in 8th grade 😅

**Comment by AyzansAlt** [comment]
im 11, 126 iq, idk how my mum made me do an iq test.

**Comment by grngxd** [comment]
im in year 6 lol

**Comment by grngxd** [comment]
in the uk we call em indices

**Comment by AyzansAlt** [comment]
`pip3 install msrmb`

**Comment by grngxd** [comment]
+ congrats to `1.41421356^2 `years of this project exisiting.

**Comment by moeenio** [comment]
Please don't do so many messages, we're cluttering the thread.

**Comment by grngxd** [comment]
sorry

**Comment by micahlt** [comment]
@locness3 The site's structure has been rebuilt with CSS grid and is now fully responsive.

**Comment by moeenio** [comment]
yay
