### ISSUE TITLE
Contact button does not work

### ISSUE THREAD

**Issue by sweezyio** [micahlt/micahlt.github.io#8]
**Problem:**
There is no contact section. Therefore nothing happens when contact buttons/links are clicked.

**Expected Functionality:**
Upon clicking a "Contact" button or link, you should be brought to the contact section of the page.

**Proposed Solution:**
Create a contact section.

**Comment by micahlt** [comment]
That's being worked on, thanks for the issue.

**Comment by grngxd** [comment]
*closed*

**Comment by grngxd** [comment]
hey *cough* archon *cough*

**Comment by micahlt** [comment]
@AyzansAlt Yes?

**Comment by grngxd** [comment]
idk I didn't think I'd get this far...

**Comment by micahlt** [comment]
Uh

**Comment by micahlt** [comment]
This has been fixed on the new v2 site.
