### ISSUE TITLE
Uploading Dark mode toggle

### ISSUE THREAD

**Issue by grngxd** [micahlt/micahlt.github.io#9]
I wanted to upload a feather icon to go to my youtube channel, but when I upload it, it's misaligned.
Any thoughts? [Screenshot](https://prnt.sc/sjlpao)

`    <div class="nav-links"><a href="#">CONTACT</a><a href="#projects">PROJECTS & EXPERIMENTS</a><a href="https://www.youtube.com/channel/UCaHeNHQ5AFkPyFnekFs2jWg/"><img src="assets/youtube.svg"></a><a href="#" class="darkmode-toggle"><i id="darkmode" class="feather icon-moon"></i></a></div>`

**Comment by micahlt** [comment]
Hmm... not sure.  This website is often unstable and it wasn't meant to be duplicated, so I can't guarantee any support.
